# Site settings
title: Blog of biggan
SEOTitle: biggan的博客
header-img: img/post-bg-coffee.jpeg
email: bigganbing@gmail.com
description: "Just do it."
keyword: "NLP,ML,rookie"
url: "http://bigganbing.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/bigganbing/bigganbing.github.io.git" # you code repository

# Sidebar settings  侧边栏
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Coding fun!"
sidebar-avatar: /img/金木.jpeg    # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings  社交账号
RSS: true
# weibo_username:     
# zhihu_username:     
github_username:    bigganbing
#facebook_username:  
#jianshu_username:   
# twitter_username:   



# Build settings   
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 8  #一页放文章数量
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]

plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: True    #是否开启Gitalk评论
  clientID: 5eeb169863955b40df52                           #生成的clientID
  clientSecret: 4bfc08478c50c50b883700729d9c66cfaec17b65   #生成的clientSecret
  repo: bigganbing.github.io    #仓库名称
  owner: bigganbing   #github用户名
  admin: bigganbing
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68


#Google Analytics
#ga_track_id: 'UA-127060267-1'            # Format: UA-xxxxxx-xx
#ga_domain:auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
friends: [
 {
        title: "CZH的Blog",
        href: "https://viewsetting.github.io"
    },
 {
        title: "PerfectPan",
        href: "http://www.perfectpan.org"
    },
 {
        title: "SamHX",
        href: "https://www.cnblogs.com/samhx"
    },
 {
        title: "Yisin",
        href: "https://yisin.top"
    }
]
